openapi: 3.0.3
info:
  title: Ciao multi-segment context dummy API
  description: |
    # Overview
    Dummy API created for testing purposes.
  version: '2.0'
  
servers:
  - url: https://api.development.tax.service.gov.uk
    description: Development
  - url: https://api.qa.tax.service.gov.uk
    description: QA
    
components:
  parameters:
    acceptHeader:
      name: Accept
      in: header
      schema:
        type: string
        enum: [
          "application/vnd.hmrc.2.0+json"
        ]
      required: true
      
    friend:
      name: friend
      in: path
      style: simple
      schema:
        type: string
      required: true
        
    city:    
      name: city
      in: path
      style: simple
      schema:
        type: string
      required: true
  
paths:
  /ciao/hey/welcome/:
    get:
      tags:
      - ciao
      summary: dummy Ciao resource
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example: 
                {
                  "message":"Ciao!"
                }
      security:
      - {}
      
  /ciao/hey/welcome/{friend}:
    get:
      tags:
      - ciao
      summary: dummy Ciao Friend resource
      operationId: dummyCiaoFriendresource
      parameters:
      - $ref: '#/components/parameters/friend'
      - $ref: '#/components/parameters/acceptHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example: 
                {
                  "message":"Ciao Dave!"
                }
      security:
      - {}
      
  /ciao/hey/welcome/{friend}/{city}:
    get:
      tags:
      - ciao
      summary: dummy Ciao Friend & City resource
      operationId: dummyCiaoFriend&Cityresource
      parameters:
      - $ref: '#/components/parameters/friend'
      - $ref: '#/components/parameters/city'
      - $ref: '#/components/parameters/acceptHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example: 
                {
                  "message":"Ciao Dave! Welcome to London!"
                }
      security:
      - {}
